using FDNS.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FNDS.Persistence.Configurations
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasKey(x => x.Id).IsClustered();

            builder.Property(c => c.FullName).HasMaxLength(50).IsRequired(true);
            builder.Property(c => c.Code).HasMaxLength(2).IsFixedLength(true).IsRequired(true);

            builder.HasIndex(c => c.Code).IsClustered(false).IsUnique();
            builder.HasIndex(c => c.FullName).IsClustered(false).IsUnique();

            ushort cnt = 1;
            builder.HasData(
                new Country { Id = cnt++, FullName = "Afghanistan", Code = "AF", Extension = 93 },
                new Country { Id = cnt++, FullName = "Albania", Code = "AL", Extension = 355 },
                new Country { Id = cnt++, FullName = "Algeria", Code = "DZ", Extension = 213 },
                new Country { Id = cnt++, FullName = "American Samoa", Code = "AS", Extension = 1 },
                new Country { Id = cnt++, FullName = "Andorra", Code = "AD", Extension = 376 },
                new Country { Id = cnt++, FullName = "Angola", Code = "AO", Extension = 244 },
                new Country { Id = cnt++, FullName = "Anguilla", Code = "AI", Extension = 1 },
                new Country { Id = cnt++, FullName = "Antarctica", Code = "AQ", Extension = 672 },
                new Country { Id = cnt++, FullName = "Antigua and Barbuda", Code = "AG", Extension = 1 },
                new Country { Id = cnt++, FullName = "Argentina", Code = "AR", Extension = 54 },
                new Country { Id = cnt++, FullName = "Armenia", Code = "AM", Extension = 374 },
                new Country { Id = cnt++, FullName = "Aruba", Code = "AW", Extension = 297 },
                new Country { Id = cnt++, FullName = "Australia", Code = "AU", Extension = 61 },
                new Country { Id = cnt++, FullName = "Austria", Code = "AT", Extension = 43 },
                new Country { Id = cnt++, FullName = "Azerbaijan", Code = "AZ", Extension = 994 },
                new Country { Id = cnt++, FullName = "Bahamas", Code = "BS", Extension = 1 },
                new Country { Id = cnt++, FullName = "Bahrain", Code = "BH", Extension = 973 },
                new Country { Id = cnt++, FullName = "Bangladesh", Code = "BD", Extension = 880 },
                new Country { Id = cnt++, FullName = "Barbados", Code = "BB", Extension = 1 },
                new Country { Id = cnt++, FullName = "Belarus", Code = "BY", Extension = 375 },
                new Country { Id = cnt++, FullName = "Belgium", Code = "BE", Extension = 32 },
                new Country { Id = cnt++, FullName = "Belize", Code = "BZ", Extension = 501 },
                new Country { Id = cnt++, FullName = "Benin", Code = "BJ", Extension = 229 },
                new Country { Id = cnt++, FullName = "Bermuda", Code = "BM", Extension = 1 },
                new Country { Id = cnt++, FullName = "Bhutan", Code = "BT", Extension = 975 },
                new Country { Id = cnt++, FullName = "Bolivia", Code = "BO", Extension = 591 },
                new Country { Id = cnt++, FullName = "Bosnia and Herzegovina", Code = "BA", Extension = 387 },
                new Country { Id = cnt++, FullName = "Botswana", Code = "BW", Extension = 267 },
                new Country { Id = cnt++, FullName = "Bouvet Island", Code = "BV", Extension = 55 },
                new Country { Id = cnt++, FullName = "Brazil", Code = "BR", Extension = 55 },
                new Country { Id = cnt++, FullName = "Brunei Darussalam", Code = "BN", Extension = 673 },
                new Country { Id = cnt++, FullName = "Bulgaria", Code = "BG", Extension = 359 },
                new Country { Id = cnt++, FullName = "Burkina Faso", Code = "BF", Extension = 226 },
                new Country { Id = cnt++, FullName = "Burundi", Code = "BI", Extension = 257 },
                new Country { Id = cnt++, FullName = "Cambodia", Code = "KH", Extension = 855 },
                new Country { Id = cnt++, FullName = "Cameroon", Code = "CM", Extension = 237 },
                new Country { Id = cnt++, FullName = "Canada", Code = "CA", Extension = 1 },
                new Country { Id = cnt++, FullName = "Cape Verde", Code = "CV", Extension = 238 },
                new Country { Id = cnt++, FullName = "Cayman Islands", Code = "KY", Extension = 1 },
                new Country { Id = cnt++, FullName = "Central African Republic", Code = "CF", Extension = 236 },
                new Country { Id = cnt++, FullName = "Chad", Code = "TD", Extension = 235 },
                new Country { Id = cnt++, FullName = "Chile", Code = "CL", Extension = 56 },
                new Country { Id = cnt++, FullName = "China", Code = "CN", Extension = 86 },
                new Country { Id = cnt++, FullName = "Christmas Island", Code = "CX", Extension = 61 },
                new Country { Id = cnt++, FullName = "Cocos Islands", Code = "CC", Extension = 61 },
                new Country { Id = cnt++, FullName = "Colombia", Code = "CO", Extension = 57 },
                new Country { Id = cnt++, FullName = "Comoros", Code = "KM", Extension = 269 },
                new Country { Id = cnt++, FullName = "Congo", Code = "CD", Extension = 243 },
                new Country { Id = cnt++, FullName = "Cook Islands", Code = "CK", Extension = 682 },
                new Country { Id = cnt++, FullName = "Costa Rica", Code = "CR", Extension = 506 },
                new Country { Id = cnt++, FullName = "Cote D'Ivoire", Code = "CI", Extension = 225 },
                new Country { Id = cnt++, FullName = "Croatia", Code = "HR", Extension = 385 },
                new Country { Id = cnt++, FullName = "Curacao", Code = "CW", Extension = 599 },
                new Country { Id = cnt++, FullName = "Cyprus", Code = "CY", Extension = 357 },
                new Country { Id = cnt++, FullName = "Czech Republic", Code = "CZ", Extension = 420 },
                new Country { Id = cnt++, FullName = "Denmark", Code = "DK", Extension = 45 },
                new Country { Id = cnt++, FullName = "Djibouti", Code = "DJ", Extension = 253 },
                new Country { Id = cnt++, FullName = "Dominica", Code = "DM", Extension = 1 },
                new Country { Id = cnt++, FullName = "Dominican Republic", Code = "DO", Extension = 1 },
                new Country { Id = cnt++, FullName = "East Timor", Code = "TL", Extension = 670 },
                new Country { Id = cnt++, FullName = "Ecuador", Code = "EC", Extension = 593 },
                new Country { Id = cnt++, FullName = "Egypt", Code = "EG", Extension = 20 },
                new Country { Id = cnt++, FullName = "El Salvador", Code = "SV", Extension = 503 },
                new Country { Id = cnt++, FullName = "Equatorial Guinea", Code = "CQ", Extension = 240 },
                new Country { Id = cnt++, FullName = "Eritrea", Code = "ER", Extension = 291 },
                new Country { Id = cnt++, FullName = "Estonia", Code = "EE", Extension = 372 },
                new Country { Id = cnt++, FullName = "Ethiopia", Code = "ET", Extension = 251 },
                new Country { Id = cnt++, FullName = "Falkland Islands", Code = "FK", Extension = 500 },
                new Country { Id = cnt++, FullName = "Faroe Islands", Code = "FO", Extension = 298 },
                new Country { Id = cnt++, FullName = "Fiji", Code = "FJ", Extension = 679 },
                new Country { Id = cnt++, FullName = "Finland", Code = "FI", Extension = 358 },
                new Country { Id = cnt++, FullName = "France", Code = "FR", Extension = 33 },
                new Country { Id = cnt++, FullName = "French Guiana", Code = "GF", Extension = 594 },
                new Country { Id = cnt++, FullName = "French Polynesia", Code = "PF", Extension = 689 },
                new Country { Id = cnt++, FullName = "Gabon", Code = "GA", Extension = 241 },
                new Country { Id = cnt++, FullName = "Gambia", Code = "GM", Extension = 220 },
                new Country { Id = cnt++, FullName = "Georgia", Code = "GE", Extension = 995 },
                new Country { Id = cnt++, FullName = "Germany", Code = "DE", Extension = 49 },
                new Country { Id = cnt++, FullName = "Ghana", Code = "GH", Extension = 233 },
                new Country { Id = cnt++, FullName = "Gibraltar", Code = "GI", Extension = 350 },
                new Country { Id = cnt++, FullName = "Greece", Code = "GR", Extension = 30 },
                new Country { Id = cnt++, FullName = "Greenland", Code = "GL", Extension = 299 },
                new Country { Id = cnt++, FullName = "Grenada", Code = "GD", Extension = 1 },
                new Country { Id = cnt++, FullName = "Guadeloupe", Code = "GP", Extension = 590 },
                new Country { Id = cnt++, FullName = "Guam", Code = "GU", Extension = 1 },
                new Country { Id = cnt++, FullName = "Guatemala", Code = "GT", Extension = 502 },
                new Country { Id = cnt++, FullName = "Guernsey", Code = "GG", Extension = 44 },
                new Country { Id = cnt++, FullName = "Guinea", Code = "GN", Extension = 224 },
                new Country { Id = cnt++, FullName = "Guinea-Bissau", Code = "GW", Extension = 245 },
                new Country { Id = cnt++, FullName = "Guyana", Code = "GY", Extension = 592 },
                new Country { Id = cnt++, FullName = "Haiti", Code = "HT", Extension = 509 },
                new Country { Id = cnt++, FullName = "Honduras", Code = "HN", Extension = 504 },
                new Country { Id = cnt++, FullName = "Hong Kong", Code = "HK", Extension = 852 },
                new Country { Id = cnt++, FullName = "Hungary", Code = "HU", Extension = 36 },
                new Country { Id = cnt++, FullName = "Iceland", Code = "IS", Extension = 354 },
                new Country { Id = cnt++, FullName = "India", Code = "IN", Extension = 91 },
                new Country { Id = cnt++, FullName = "Indonesia", Code = "ID", Extension = 62 },
                new Country { Id = cnt++, FullName = "Iraq", Code = "IR", Extension = 964 },
                new Country { Id = cnt++, FullName = "Ireland", Code = "IE", Extension = 353 },
                new Country { Id = cnt++, FullName = "Isle of Man", Code = "IM", Extension = 44 },
                new Country { Id = cnt++, FullName = "Israel", Code = "IL", Extension = 972 },
                new Country { Id = cnt++, FullName = "Italy", Code = "IT", Extension = 39 },
                new Country { Id = cnt++, FullName = "Japan", Code = "JP", Extension = 81 },
                new Country { Id = cnt++, FullName = "Jersey", Code = "JE", Extension = 44 },
                new Country { Id = cnt++, FullName = "Jordan", Code = "JO", Extension = 962 },
                new Country { Id = cnt++, FullName = "Kazakhstan", Code = "KZ", Extension = 7 },
                new Country { Id = cnt++, FullName = "Kenya", Code = "KE", Extension = 254 },
                new Country { Id = cnt++, FullName = "Kiribati", Code = "KI", Extension = 686 },
                new Country { Id = cnt++, FullName = "Kuwait", Code = "KW", Extension = 965 },
                new Country { Id = cnt++, FullName = "Kyrgyzstan", Code = "KG", Extension = 996 },
                new Country { Id = cnt++, FullName = "Laos", Code = "LA", Extension = 856 },
                new Country { Id = cnt++, FullName = "Latvia", Code = "LV", Extension = 371 },
                new Country { Id = cnt++, FullName = "Lebanon", Code = "LB", Extension = 961 },
                new Country { Id = cnt++, FullName = "Lesotho", Code = "LS", Extension = 266 },
                new Country { Id = cnt++, FullName = "Liberia", Code = "LR", Extension = 231 },
                new Country { Id = cnt++, FullName = "Libya", Code = "LY", Extension = 218 },
                new Country { Id = cnt++, FullName = "Liechtenstein", Code = "LI", Extension = 423 },
                new Country { Id = cnt++, FullName = "Lithuania", Code = "LT", Extension = 370 },
                new Country { Id = cnt++, FullName = "Luxembourg", Code = "LU", Extension = 352 },
                new Country { Id = cnt++, FullName = "Macau", Code = "MO", Extension = 853 },
                new Country { Id = cnt++, FullName = "Macedonia", Code = "MK", Extension = 389 },
                new Country { Id = cnt++, FullName = "Madagascar", Code = "MG", Extension = 261 },
                new Country { Id = cnt++, FullName = "Malawi", Code = "MW", Extension = 265 },
                new Country { Id = cnt++, FullName = "Malaysia", Code = "MY", Extension = 60 },
                new Country { Id = cnt++, FullName = "Maldives", Code = "MV", Extension = 960 },
                new Country { Id = cnt++, FullName = "Mali", Code = "ML", Extension = 223 },
                new Country { Id = cnt++, FullName = "Malta", Code = "MT", Extension = 356 },
                new Country { Id = cnt++, FullName = "Marshall Islands", Code = "MH", Extension = 692 },
                new Country { Id = cnt++, FullName = "Martinique", Code = "MQ", Extension = 596 },
                new Country { Id = cnt++, FullName = "Mauritania", Code = "MR", Extension = 222 },
                new Country { Id = cnt++, FullName = "Mauritius", Code = "MU", Extension = 230 },
                new Country { Id = cnt++, FullName = "Mayotte", Code = "YT", Extension = 262 },
                new Country { Id = cnt++, FullName = "Mexico", Code = "MX", Extension = 52 },
                new Country { Id = cnt++, FullName = "Micronesia", Code = "FM", Extension = 691 },
                new Country { Id = cnt++, FullName = "Moldova", Code = "MD", Extension = 373 },
                new Country { Id = cnt++, FullName = "Monaco", Code = "MC", Extension = 277 },
                new Country { Id = cnt++, FullName = "Mongolia", Code = "MN", Extension = 976 },
                new Country { Id = cnt++, FullName = "Montenegro", Code = "ME", Extension = 382 },
                new Country { Id = cnt++, FullName = "Montserrat", Code = "MS", Extension = 1 },
                new Country { Id = cnt++, FullName = "Morocco", Code = "MA", Extension = 212 },
                new Country { Id = cnt++, FullName = "Mozambique", Code = "MZ", Extension = 258 },
                new Country { Id = cnt++, FullName = "Myanmar", Code = "MM", Extension = 95 },
                new Country { Id = cnt++, FullName = "Namibia", Code = "NA", Extension = 264 },
                new Country { Id = cnt++, FullName = "Nauru", Code = "NR", Extension = 674 },
                new Country { Id = cnt++, FullName = "Nepal", Code = "NP", Extension = 977 },
                new Country { Id = cnt++, FullName = "Netherlands", Code = "NL", Extension = 31 },
                new Country { Id = cnt++, FullName = "Netherlands Antilles", Code = "AN", Extension = 599 },
                new Country { Id = cnt++, FullName = "New Caledonia", Code = "NC", Extension = 687 },
                new Country { Id = cnt++, FullName = "New Zealand", Code = "NZ", Extension = 64 },
                new Country { Id = cnt++, FullName = "Nicaragua", Code = "NI", Extension = 505 },
                new Country { Id = cnt++, FullName = "Niger", Code = "NE", Extension = 227 },
                new Country { Id = cnt++, FullName = "Nigeria", Code = "NG", Extension = 234 },
                new Country { Id = cnt++, FullName = "Niue", Code = "NU", Extension = 683 },
                new Country { Id = cnt++, FullName = "Norfolk Island", Code = "NF", Extension = 672 },
                new Country { Id = cnt++, FullName = "Northern Mariana Isls", Code = "MP", Extension = 1 },
                new Country { Id = cnt++, FullName = "Norway", Code = "NO", Extension = 47 },
                new Country { Id = cnt++, FullName = "Oman", Code = "OM", Extension = 968 },
                new Country { Id = cnt++, FullName = "Pakistan", Code = "PK", Extension = 92 },
                new Country { Id = cnt++, FullName = "Palau", Code = "PW", Extension = 680 },
                new Country { Id = cnt++, FullName = "Papua New Guinea", Code = "PG", Extension = 675 },
                new Country { Id = cnt++, FullName = "Paraguay", Code = "PY", Extension = 595 },
                new Country { Id = cnt++, FullName = "Peru", Code = "PE", Extension = 51 },
                new Country { Id = cnt++, FullName = "Philippines", Code = "PH", Extension = 63 },
                new Country { Id = cnt++, FullName = "Pitcairn", Code = "PN", Extension = 64 },
                new Country { Id = cnt++, FullName = "Poland", Code = "PL", Extension = 48 },
                new Country { Id = cnt++, FullName = "Portugal", Code = "PT", Extension = 351 },
                new Country { Id = cnt++, FullName = "Puerto Rico", Code = "PR", Extension = 1 },
                new Country { Id = cnt++, FullName = "Qatar", Code = "QA", Extension = 974 },
                new Country { Id = cnt++, FullName = "Reunion", Code = "RE", Extension = 262 },
                new Country { Id = cnt++, FullName = "Romania", Code = "RO", Extension = 40 },
                new Country { Id = cnt++, FullName = "Rwanda", Code = "RW", Extension = 250 },
                new Country { Id = cnt++, FullName = "Saint Kitts and Nevis", Code = "KN", Extension = 1 },
                new Country { Id = cnt++, FullName = "Saint Lucia", Code = "LC", Extension = 1 },
                new Country { Id = cnt++, FullName = "Samoa", Code = "WS", Extension = 685 },
                new Country { Id = cnt++, FullName = "San Marino", Code = "SM", Extension = 378 },
                new Country { Id = cnt++, FullName = "Sao Tome and Principe", Code = "ST", Extension = 239 },
                new Country { Id = cnt++, FullName = "Saudi Arabia", Code = "SA", Extension = 966 },
                new Country { Id = cnt++, FullName = "Senegal", Code = "SN", Extension = 221 },
                new Country { Id = cnt++, FullName = "Serbia", Code = "RS", Extension = 381 },
                new Country { Id = cnt++, FullName = "Seychelles", Code = "SC", Extension = 248 },
                new Country { Id = cnt++, FullName = "Sierra Leone", Code = "SL", Extension = 232 },
                new Country { Id = cnt++, FullName = "Singapore", Code = "SG", Extension = 65 },
                new Country { Id = cnt++, FullName = "Slovak Republic", Code = "SK", Extension = 421 },
                new Country { Id = cnt++, FullName = "Slovenia", Code = "SI", Extension = 386 },
                new Country { Id = cnt++, FullName = "Solomon Islands", Code = "SB", Extension = 677 },
                new Country { Id = cnt++, FullName = "Somalia", Code = "SO", Extension = 252 },
                new Country { Id = cnt++, FullName = "South Africa", Code = "ZA", Extension = 27 },
                new Country { Id = cnt++, FullName = "South Korea", Code = "KR", Extension = 82 },
                new Country { Id = cnt++, FullName = "Spain", Code = "ES", Extension = 34 },
                new Country { Id = cnt++, FullName = "Sri Lanka", Code = "LK", Extension = 94 },
                new Country { Id = cnt++, FullName = "St. Vincent", Code = "VC", Extension = 1 },
                new Country { Id = cnt++, FullName = "St. Helena", Code = "SH", Extension = 290 },
                new Country { Id = cnt++, FullName = "St. Pierre and Miquelon", Code = "PM", Extension = 508 },
                new Country { Id = cnt++, FullName = "Suriname", Code = "SR", Extension = 597 },
                new Country { Id = cnt++, FullName = "Swaziland", Code = "SZ", Extension = 268 },
                new Country { Id = cnt++, FullName = "Sweden", Code = "SE", Extension = 46 },
                new Country { Id = cnt++, FullName = "Switzerland", Code = "CH", Extension = 41 },
                new Country { Id = cnt++, FullName = "Taiwan", Code = "TW", Extension = 886 },
                new Country { Id = cnt++, FullName = "Tajikistan", Code = "TJ", Extension = 992 },
                new Country { Id = cnt++, FullName = "Tanzania", Code = "TZ", Extension = 255 },
                new Country { Id = cnt++, FullName = "Thailand", Code = "TH", Extension = 66 },
                new Country { Id = cnt++, FullName = "Togo", Code = "TG", Extension = 228 },
                new Country { Id = cnt++, FullName = "Tokelau", Code = "TK", Extension = 690 },
                new Country { Id = cnt++, FullName = "Tonga", Code = "TO", Extension = 676 },
                new Country { Id = cnt++, FullName = "Trinidad and Tobago", Code = "TT", Extension = 1 },
                new Country { Id = cnt++, FullName = "Tunisia", Code = "TN", Extension = 216 },
                new Country { Id = cnt++, FullName = "Turkey", Code = "TR", Extension = 90 },
                new Country { Id = cnt++, FullName = "Turkmenistan", Code = "TM", Extension = 993 },
                new Country { Id = cnt++, FullName = "Turks and Caicos Islands", Code = "TC", Extension = 1 },
                new Country { Id = cnt++, FullName = "Tuvalu", Code = "TV", Extension = 688 },
                new Country { Id = cnt++, FullName = "Uganda", Code = "UG", Extension = 256 },
                new Country { Id = cnt++, FullName = "Ukraine", Code = "UA", Extension = 380 },
                new Country { Id = cnt++, FullName = "United Arab Emirates", Code = "AE", Extension = 971 },
                new Country { Id = cnt++, FullName = "United Kingdom", Code = "GB", Extension = 44 },
                new Country { Id = cnt++, FullName = "United States", Code = "US", Extension = 1 },
                new Country { Id = cnt++, FullName = "Uruguay", Code = "UY", Extension = 598 },
                new Country { Id = cnt++, FullName = "Uzbekistan", Code = "UZ", Extension = 998 },
                new Country { Id = cnt++, FullName = "Vanuatu", Code = "VU", Extension = 678 },
                new Country { Id = cnt++, FullName = "Vatican", Code = "VA", Extension = 379 },
                new Country { Id = cnt++, FullName = "Venezuela", Code = "VE", Extension = 58 },
                new Country { Id = cnt++, FullName = "Vietnam", Code = "VN", Extension = 84 },
                new Country { Id = cnt++, FullName = "Wallis and Futuna Isls", Code = "WF", Extension = 681 },
                new Country { Id = cnt++, FullName = "Western Sahara", Code = "EH", Extension = 212 },
                new Country { Id = cnt++, FullName = "Yemen", Code = "YE", Extension = 967 },
                new Country { Id = 226, FullName = "Zambia", Code = "ZM", Extension = 260 },
                new Country { Id = 227, FullName = "Zimbabwe", Code = "ZW", Extension = 263 });
        }
    }
}