// <auto-generated />
using System;
using FNDS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FNDS.Persistence.Migrations
{
    [DbContext(typeof(FdnsDbContext))]
    [Migration("20220603225545_AddTldTables")]
    partial class AddTldTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FDNS.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Code")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Code"), false);

                    b.HasIndex("FullName")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("FullName"), false);

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            FullName = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AL",
                            FullName = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DZ",
                            FullName = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AS",
                            FullName = "American Samoa"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AD",
                            FullName = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AO",
                            FullName = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AI",
                            FullName = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AQ",
                            FullName = "Antarctica"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AG",
                            FullName = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AR",
                            FullName = "Argentina"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AM",
                            FullName = "Armenia"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AW",
                            FullName = "Aruba"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AU",
                            FullName = "Australia"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AT",
                            FullName = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AZ",
                            FullName = "Azerbaijan"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BS",
                            FullName = "Bahamas"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BH",
                            FullName = "Bahrain"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BD",
                            FullName = "Bangladesh"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BB",
                            FullName = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BY",
                            FullName = "Belarus"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BE",
                            FullName = "Belgium"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BZ",
                            FullName = "Belize"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BJ",
                            FullName = "Benin"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BM",
                            FullName = "Bermuda"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BT",
                            FullName = "Bhutan"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BO",
                            FullName = "Bolivia"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BA",
                            FullName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BW",
                            FullName = "Botswana"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BV",
                            FullName = "Bouvet Island"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BR",
                            FullName = "Brazil"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BN",
                            FullName = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BG",
                            FullName = "Bulgaria"
                        },
                        new
                        {
                            Id = 33,
                            Code = "BF",
                            FullName = "Burkina Faso"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BI",
                            FullName = "Burundi"
                        },
                        new
                        {
                            Id = 35,
                            Code = "KH",
                            FullName = "Cambodia"
                        },
                        new
                        {
                            Id = 36,
                            Code = "CM",
                            FullName = "Cameroon"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CA",
                            FullName = "Canada"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CV",
                            FullName = "Cape Verde"
                        },
                        new
                        {
                            Id = 39,
                            Code = "KY",
                            FullName = "Cayman Islands"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CF",
                            FullName = "Central African Republic"
                        },
                        new
                        {
                            Id = 41,
                            Code = "TD",
                            FullName = "Chad"
                        },
                        new
                        {
                            Id = 42,
                            Code = "CL",
                            FullName = "Chile"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CN",
                            FullName = "China"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CX",
                            FullName = "Christmas Island"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CC",
                            FullName = "Cocos Islands"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CO",
                            FullName = "Colombia"
                        },
                        new
                        {
                            Id = 47,
                            Code = "KM",
                            FullName = "Comoros"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CD",
                            FullName = "Congo"
                        },
                        new
                        {
                            Id = 49,
                            Code = "CK",
                            FullName = "Cook Islands"
                        },
                        new
                        {
                            Id = 50,
                            Code = "CR",
                            FullName = "Costa Rica"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CI",
                            FullName = "Cote D'Ivoire"
                        },
                        new
                        {
                            Id = 52,
                            Code = "HR",
                            FullName = "Croatia"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CW",
                            FullName = "Curacao"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CY",
                            FullName = "Cyprus"
                        },
                        new
                        {
                            Id = 55,
                            Code = "CZ",
                            FullName = "Czech Republic"
                        },
                        new
                        {
                            Id = 56,
                            Code = "DK",
                            FullName = "Denmark"
                        },
                        new
                        {
                            Id = 57,
                            Code = "DJ",
                            FullName = "Djibouti"
                        },
                        new
                        {
                            Id = 58,
                            Code = "DM",
                            FullName = "Dominica"
                        },
                        new
                        {
                            Id = 59,
                            Code = "DO",
                            FullName = "Dominican Republic"
                        },
                        new
                        {
                            Id = 60,
                            Code = "TL",
                            FullName = "East Timor"
                        },
                        new
                        {
                            Id = 61,
                            Code = "EC",
                            FullName = "Ecuador"
                        },
                        new
                        {
                            Id = 62,
                            Code = "EG",
                            FullName = "Egypt"
                        },
                        new
                        {
                            Id = 63,
                            Code = "SV",
                            FullName = "El Salvador"
                        },
                        new
                        {
                            Id = 64,
                            Code = "CQ",
                            FullName = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 65,
                            Code = "ER",
                            FullName = "Eritrea"
                        },
                        new
                        {
                            Id = 66,
                            Code = "EE",
                            FullName = "Estonia"
                        },
                        new
                        {
                            Id = 67,
                            Code = "ET",
                            FullName = "Ethiopia"
                        },
                        new
                        {
                            Id = 68,
                            Code = "FK",
                            FullName = "Falkland Islands"
                        },
                        new
                        {
                            Id = 69,
                            Code = "FO",
                            FullName = "Faroe Islands"
                        },
                        new
                        {
                            Id = 70,
                            Code = "FJ",
                            FullName = "Fiji"
                        },
                        new
                        {
                            Id = 71,
                            Code = "FI",
                            FullName = "Finland"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FR",
                            FullName = "France"
                        },
                        new
                        {
                            Id = 73,
                            Code = "GF",
                            FullName = "French Guiana"
                        },
                        new
                        {
                            Id = 74,
                            Code = "PF",
                            FullName = "French Polynesia"
                        },
                        new
                        {
                            Id = 75,
                            Code = "GA",
                            FullName = "Gabon"
                        },
                        new
                        {
                            Id = 76,
                            Code = "GM",
                            FullName = "Gambia"
                        },
                        new
                        {
                            Id = 77,
                            Code = "GE",
                            FullName = "Georgia"
                        },
                        new
                        {
                            Id = 78,
                            Code = "DE",
                            FullName = "Germany"
                        },
                        new
                        {
                            Id = 79,
                            Code = "GH",
                            FullName = "Ghana"
                        },
                        new
                        {
                            Id = 80,
                            Code = "GI",
                            FullName = "Gibraltar"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GR",
                            FullName = "Greece"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GL",
                            FullName = "Greenland"
                        },
                        new
                        {
                            Id = 83,
                            Code = "GD",
                            FullName = "Grenada"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GP",
                            FullName = "Guadeloupe"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GU",
                            FullName = "Guam"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GT",
                            FullName = "Guatemala"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GG",
                            FullName = "Guernsey"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GN",
                            FullName = "Guinea"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GW",
                            FullName = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GY",
                            FullName = "Guyana"
                        },
                        new
                        {
                            Id = 91,
                            Code = "HT",
                            FullName = "Haiti"
                        },
                        new
                        {
                            Id = 92,
                            Code = "HN",
                            FullName = "Honduras"
                        },
                        new
                        {
                            Id = 93,
                            Code = "HK",
                            FullName = "Hong Kong"
                        },
                        new
                        {
                            Id = 94,
                            Code = "HU",
                            FullName = "Hungary"
                        },
                        new
                        {
                            Id = 95,
                            Code = "IS",
                            FullName = "Iceland"
                        },
                        new
                        {
                            Id = 96,
                            Code = "IN",
                            FullName = "India"
                        },
                        new
                        {
                            Id = 97,
                            Code = "ID",
                            FullName = "Indonesia"
                        },
                        new
                        {
                            Id = 98,
                            Code = "IR",
                            FullName = "Iraq"
                        },
                        new
                        {
                            Id = 99,
                            Code = "IE",
                            FullName = "Ireland"
                        },
                        new
                        {
                            Id = 100,
                            Code = "IM",
                            FullName = "Isle of Man"
                        },
                        new
                        {
                            Id = 101,
                            Code = "IL",
                            FullName = "Israel"
                        },
                        new
                        {
                            Id = 102,
                            Code = "IT",
                            FullName = "Italy"
                        },
                        new
                        {
                            Id = 103,
                            Code = "JP",
                            FullName = "Japan"
                        },
                        new
                        {
                            Id = 104,
                            Code = "JE",
                            FullName = "Jersey"
                        },
                        new
                        {
                            Id = 105,
                            Code = "JO",
                            FullName = "Jordan"
                        },
                        new
                        {
                            Id = 106,
                            Code = "KZ",
                            FullName = "Kazakhstan"
                        },
                        new
                        {
                            Id = 107,
                            Code = "KE",
                            FullName = "Kenya"
                        },
                        new
                        {
                            Id = 108,
                            Code = "KI",
                            FullName = "Kiribati"
                        },
                        new
                        {
                            Id = 109,
                            Code = "KW",
                            FullName = "Kuwait"
                        },
                        new
                        {
                            Id = 110,
                            Code = "KG",
                            FullName = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 111,
                            Code = "LA",
                            FullName = "Laos"
                        },
                        new
                        {
                            Id = 112,
                            Code = "LV",
                            FullName = "Latvia"
                        },
                        new
                        {
                            Id = 113,
                            Code = "LB",
                            FullName = "Lebanon"
                        },
                        new
                        {
                            Id = 114,
                            Code = "LS",
                            FullName = "Lesotho"
                        },
                        new
                        {
                            Id = 115,
                            Code = "LR",
                            FullName = "Liberia"
                        },
                        new
                        {
                            Id = 116,
                            Code = "LY",
                            FullName = "Libya"
                        },
                        new
                        {
                            Id = 117,
                            Code = "LI",
                            FullName = "Liechtenstein"
                        },
                        new
                        {
                            Id = 118,
                            Code = "LT",
                            FullName = "Lithuania"
                        },
                        new
                        {
                            Id = 119,
                            Code = "LU",
                            FullName = "Luxembourg"
                        },
                        new
                        {
                            Id = 120,
                            Code = "MO",
                            FullName = "Macau"
                        },
                        new
                        {
                            Id = 121,
                            Code = "MK",
                            FullName = "Macedonia"
                        },
                        new
                        {
                            Id = 122,
                            Code = "MG",
                            FullName = "Madagascar"
                        },
                        new
                        {
                            Id = 123,
                            Code = "MW",
                            FullName = "Malawi"
                        },
                        new
                        {
                            Id = 124,
                            Code = "MY",
                            FullName = "Malaysia"
                        },
                        new
                        {
                            Id = 125,
                            Code = "MV",
                            FullName = "Maldives"
                        },
                        new
                        {
                            Id = 126,
                            Code = "ML",
                            FullName = "Mali"
                        },
                        new
                        {
                            Id = 127,
                            Code = "MT",
                            FullName = "Malta"
                        },
                        new
                        {
                            Id = 128,
                            Code = "MH",
                            FullName = "Marshall Islands"
                        },
                        new
                        {
                            Id = 129,
                            Code = "MQ",
                            FullName = "Martinique"
                        },
                        new
                        {
                            Id = 130,
                            Code = "MR",
                            FullName = "Mauritania"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MU",
                            FullName = "Mauritius"
                        },
                        new
                        {
                            Id = 132,
                            Code = "YT",
                            FullName = "Mayotte"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MX",
                            FullName = "Mexico"
                        },
                        new
                        {
                            Id = 134,
                            Code = "FM",
                            FullName = "Micronesia"
                        },
                        new
                        {
                            Id = 135,
                            Code = "MD",
                            FullName = "Moldova"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MC",
                            FullName = "Monaco"
                        },
                        new
                        {
                            Id = 137,
                            Code = "MN",
                            FullName = "Mongolia"
                        },
                        new
                        {
                            Id = 138,
                            Code = "ME",
                            FullName = "Montenegro"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MS",
                            FullName = "Montserrat"
                        },
                        new
                        {
                            Id = 140,
                            Code = "MA",
                            FullName = "Morocco"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MZ",
                            FullName = "Mozambique"
                        },
                        new
                        {
                            Id = 142,
                            Code = "MM",
                            FullName = "Myanmar"
                        },
                        new
                        {
                            Id = 143,
                            Code = "NA",
                            FullName = "Namibia"
                        },
                        new
                        {
                            Id = 144,
                            Code = "NR",
                            FullName = "Nauru"
                        },
                        new
                        {
                            Id = 145,
                            Code = "NP",
                            FullName = "Nepal"
                        },
                        new
                        {
                            Id = 146,
                            Code = "NL",
                            FullName = "Netherlands"
                        },
                        new
                        {
                            Id = 147,
                            Code = "AN",
                            FullName = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 148,
                            Code = "NC",
                            FullName = "New Caledonia"
                        },
                        new
                        {
                            Id = 149,
                            Code = "NZ",
                            FullName = "New Zealand"
                        },
                        new
                        {
                            Id = 150,
                            Code = "NI",
                            FullName = "Nicaragua"
                        },
                        new
                        {
                            Id = 151,
                            Code = "NE",
                            FullName = "Niger"
                        },
                        new
                        {
                            Id = 152,
                            Code = "NG",
                            FullName = "Nigeria"
                        },
                        new
                        {
                            Id = 153,
                            Code = "NU",
                            FullName = "Niue"
                        },
                        new
                        {
                            Id = 154,
                            Code = "NF",
                            FullName = "Norfolk Island"
                        },
                        new
                        {
                            Id = 155,
                            Code = "MP",
                            FullName = "Northern Mariana Isls"
                        },
                        new
                        {
                            Id = 156,
                            Code = "NO",
                            FullName = "Norway"
                        },
                        new
                        {
                            Id = 157,
                            Code = "OM",
                            FullName = "Oman"
                        },
                        new
                        {
                            Id = 158,
                            Code = "PK",
                            FullName = "Pakistan"
                        },
                        new
                        {
                            Id = 159,
                            Code = "PW",
                            FullName = "Palau"
                        },
                        new
                        {
                            Id = 160,
                            Code = "PG",
                            FullName = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 161,
                            Code = "PY",
                            FullName = "Paraguay"
                        },
                        new
                        {
                            Id = 162,
                            Code = "PE",
                            FullName = "Peru"
                        },
                        new
                        {
                            Id = 163,
                            Code = "PH",
                            FullName = "Philippines"
                        },
                        new
                        {
                            Id = 164,
                            Code = "PN",
                            FullName = "Pitcairn"
                        },
                        new
                        {
                            Id = 165,
                            Code = "PL",
                            FullName = "Poland"
                        },
                        new
                        {
                            Id = 166,
                            Code = "PT",
                            FullName = "Portugal"
                        },
                        new
                        {
                            Id = 167,
                            Code = "PR",
                            FullName = "Puerto Rico"
                        },
                        new
                        {
                            Id = 168,
                            Code = "QA",
                            FullName = "Qatar"
                        },
                        new
                        {
                            Id = 169,
                            Code = "RE",
                            FullName = "Reunion"
                        },
                        new
                        {
                            Id = 170,
                            Code = "RO",
                            FullName = "Romania"
                        },
                        new
                        {
                            Id = 171,
                            Code = "RW",
                            FullName = "Rwanda"
                        },
                        new
                        {
                            Id = 172,
                            Code = "KN",
                            FullName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 173,
                            Code = "LC",
                            FullName = "Saint Lucia"
                        },
                        new
                        {
                            Id = 174,
                            Code = "WS",
                            FullName = "Samoa"
                        },
                        new
                        {
                            Id = 175,
                            Code = "SM",
                            FullName = "San Marino"
                        },
                        new
                        {
                            Id = 176,
                            Code = "ST",
                            FullName = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 177,
                            Code = "SA",
                            FullName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 178,
                            Code = "SN",
                            FullName = "Senegal"
                        },
                        new
                        {
                            Id = 179,
                            Code = "RS",
                            FullName = "Serbia"
                        },
                        new
                        {
                            Id = 180,
                            Code = "SC",
                            FullName = "Seychelles"
                        },
                        new
                        {
                            Id = 181,
                            Code = "SL",
                            FullName = "Sierra Leone"
                        },
                        new
                        {
                            Id = 182,
                            Code = "SG",
                            FullName = "Singapore"
                        },
                        new
                        {
                            Id = 183,
                            Code = "SK",
                            FullName = "Slovak Republic"
                        },
                        new
                        {
                            Id = 184,
                            Code = "SI",
                            FullName = "Slovenia"
                        },
                        new
                        {
                            Id = 185,
                            Code = "SB",
                            FullName = "Solomon Islands"
                        },
                        new
                        {
                            Id = 186,
                            Code = "SO",
                            FullName = "Somalia"
                        },
                        new
                        {
                            Id = 187,
                            Code = "ZA",
                            FullName = "South Africa"
                        },
                        new
                        {
                            Id = 188,
                            Code = "KR",
                            FullName = "South Korea"
                        },
                        new
                        {
                            Id = 189,
                            Code = "ES",
                            FullName = "Spain"
                        },
                        new
                        {
                            Id = 190,
                            Code = "LK",
                            FullName = "Sri Lanka"
                        },
                        new
                        {
                            Id = 191,
                            Code = "VC",
                            FullName = "St. Vincent"
                        },
                        new
                        {
                            Id = 192,
                            Code = "SH",
                            FullName = "St. Helena"
                        },
                        new
                        {
                            Id = 193,
                            Code = "PM",
                            FullName = "St. Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 194,
                            Code = "SR",
                            FullName = "Suriname"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SZ",
                            FullName = "Swaziland"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SE",
                            FullName = "Sweden"
                        },
                        new
                        {
                            Id = 197,
                            Code = "CH",
                            FullName = "Switzerland"
                        },
                        new
                        {
                            Id = 198,
                            Code = "TW",
                            FullName = "Taiwan"
                        },
                        new
                        {
                            Id = 199,
                            Code = "TJ",
                            FullName = "Tajikistan"
                        },
                        new
                        {
                            Id = 200,
                            Code = "TZ",
                            FullName = "Tanzania"
                        },
                        new
                        {
                            Id = 201,
                            Code = "TH",
                            FullName = "Thailand"
                        },
                        new
                        {
                            Id = 202,
                            Code = "TG",
                            FullName = "Togo"
                        },
                        new
                        {
                            Id = 203,
                            Code = "TK",
                            FullName = "Tokelau"
                        },
                        new
                        {
                            Id = 204,
                            Code = "TO",
                            FullName = "Tonga"
                        },
                        new
                        {
                            Id = 205,
                            Code = "TT",
                            FullName = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 206,
                            Code = "TN",
                            FullName = "Tunisia"
                        },
                        new
                        {
                            Id = 207,
                            Code = "TR",
                            FullName = "Turkey"
                        },
                        new
                        {
                            Id = 208,
                            Code = "TM",
                            FullName = "Turkmenistan"
                        },
                        new
                        {
                            Id = 209,
                            Code = "TC",
                            FullName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 210,
                            Code = "TV",
                            FullName = "Tuvalu"
                        },
                        new
                        {
                            Id = 211,
                            Code = "UG",
                            FullName = "Uganda"
                        },
                        new
                        {
                            Id = 212,
                            Code = "UA",
                            FullName = "Ukraine"
                        },
                        new
                        {
                            Id = 213,
                            Code = "AE",
                            FullName = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 214,
                            Code = "GB",
                            FullName = "United Kingdom"
                        },
                        new
                        {
                            Id = 215,
                            Code = "US",
                            FullName = "United States"
                        },
                        new
                        {
                            Id = 216,
                            Code = "UY",
                            FullName = "Uruguay"
                        },
                        new
                        {
                            Id = 217,
                            Code = "UZ",
                            FullName = "Uzbekistan"
                        },
                        new
                        {
                            Id = 218,
                            Code = "VU",
                            FullName = "Vanuatu"
                        },
                        new
                        {
                            Id = 219,
                            Code = "VA",
                            FullName = "Vatican"
                        },
                        new
                        {
                            Id = 220,
                            Code = "VE",
                            FullName = "Venezuela"
                        },
                        new
                        {
                            Id = 221,
                            Code = "VN",
                            FullName = "Vietnam"
                        },
                        new
                        {
                            Id = 222,
                            Code = "WF",
                            FullName = "Wallis and Futuna Isls"
                        },
                        new
                        {
                            Id = 223,
                            Code = "EH",
                            FullName = "Western Sahara"
                        },
                        new
                        {
                            Id = 224,
                            Code = "YE",
                            FullName = "Yemen"
                        },
                        new
                        {
                            Id = 225,
                            Code = "ZR",
                            FullName = "Zaire"
                        },
                        new
                        {
                            Id = 226,
                            Code = "ZM",
                            FullName = "Zambia"
                        },
                        new
                        {
                            Id = 227,
                            Code = "ZW",
                            FullName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("FDNS.Domain.Models.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoRenew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDomainPrivacy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<int>("NamecheapId")
                        .HasColumnType("int");

                    b.Property<int?>("NamecheapOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("NamecheapTransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NamecheapId")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("NamecheapId"), false);

                    b.HasIndex("UserId");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("FDNS.Domain.Models.DomainContacts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Fax number in the format +NNN.NNNNNNNNNN");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Phone number in the format +NNN.NNNNNNNNNN");

                    b.Property<string>("PhoneExt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateProvinceChoice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DomainId");

                    b.ToTable("DomainContacts");
                });

            modelBuilder.Entity("FDNS.Domain.Models.ProductionDomainPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("AdditionalCost")
                        .HasColumnType("float");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("DurationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("RegularPrice")
                        .HasColumnType("float");

                    b.Property<double>("UserPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductionDomainPricing");
                });

            modelBuilder.Entity("FDNS.Domain.Models.ProductionTLD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApiRegisterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApiRenewable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApiTransferable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisableModContact")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisableWGAllot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEppRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIncludeInExtendedSearchOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupportsIDN")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRegisterYears")
                        .HasColumnType("int");

                    b.Property<int>("MaxRenewYears")
                        .HasColumnType("int");

                    b.Property<int>("MaxTransferYears")
                        .HasColumnType("int");

                    b.Property<int>("MinRegisterYears")
                        .HasColumnType("int");

                    b.Property<int>("MinRenewYears")
                        .HasColumnType("int");

                    b.Property<int>("MinTransferYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonRealTime")
                        .HasColumnType("bit");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionTLDs");
                });

            modelBuilder.Entity("FDNS.Domain.Models.SandboxDomainPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("AdditionalCost")
                        .HasColumnType("float");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("DurationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("RegularPrice")
                        .HasColumnType("float");

                    b.Property<double>("UserPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SandboxDomainPricing");
                });

            modelBuilder.Entity("FDNS.Domain.Models.SandboxTLD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApiRegisterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApiRenewable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApiTransferable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisableModContact")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisableWGAllot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEppRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIncludeInExtendedSearchOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupportsIDN")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRegisterYears")
                        .HasColumnType("int");

                    b.Property<int>("MaxRenewYears")
                        .HasColumnType("int");

                    b.Property<int>("MaxTransferYears")
                        .HasColumnType("int");

                    b.Property<int>("MinRegisterYears")
                        .HasColumnType("int");

                    b.Property<int>("MinRenewYears")
                        .HasColumnType("int");

                    b.Property<int>("MinTransferYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonRealTime")
                        .HasColumnType("bit");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SandboxTLDs");
                });

            modelBuilder.Entity("FDNS.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("AccountBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FDNS.Domain.Models.UserContacts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Address2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("DefaultYN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Specifies whether this particular set of contacts should be set as PRIMARY for the account");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Fax number in the format +NNN.NNNNNNNNNN");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Organization")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Phone number in the format +NNN.NNNNNNNNNN");

                    b.Property<string>("PhoneExt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StateProvinceChoice")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("781ac221-b109-453b-a525-95bc9ec87678"),
                            ConcurrencyStamp = "cd29fe3c-0292-4c0b-a620-1b12e17100a4",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("fd55fe70-7497-4f55-980e-0d936d6bee4e"),
                            ConcurrencyStamp = "13f549a6-a363-486e-a287-2f1bd3154037",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FDNS.Domain.Models.Domain", b =>
                {
                    b.HasOne("FDNS.Domain.Models.User", "User")
                        .WithMany("Domains")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FDNS.Domain.Models.DomainContacts", b =>
                {
                    b.HasOne("FDNS.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FDNS.Domain.Models.Domain", "Domain")
                        .WithMany("Contacts")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("FDNS.Domain.Models.UserContacts", b =>
                {
                    b.HasOne("FDNS.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FDNS.Domain.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FDNS.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FDNS.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FDNS.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FDNS.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FDNS.Domain.Models.Domain", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("FDNS.Domain.Models.User", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
